meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: zookeeper
    templates:
    - name: zookeeper
      release: bigdata
    instances: 1
    persistent_disk: 2048
    resource_pool: small_z1
    networks: (( param "please set just_install_package networks" ))

networks: (( param "please set networks" ))

properties: {}
